#pragma once

#include <nlohmann/json.hpp>

#define DECLARE_SERIALIZABLE(Type, ...) NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Type, __VA_ARGS__)
#define BEGIN_SERIALIZER_NAMESPACE NLOHMANN_JSON_NAMESPACE_BEGIN
#define END_SERIALIZER_NAMESPACE NLOHMANN_JSON_NAMESPACE_END
